/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;
import DAO.BulletinDAO;
import DAO.TrimestreDAO;
import Modele.Bulletin;
import Modele.Trimestre;
import static Vue.OneClass.inscription;
import static Vue.Classes.classe;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Affiche les trimestres et les bulletins
 * @author kevin
 */
public class SchoolReport extends javax.swing.JFrame {
    
    ArrayList<Trimestre> allQuarters =new ArrayList<>(); //Tous les trimestres de la table
    TrimestreDAO quarterdao;
    Trimestre trimestre=new Trimestre(); //Trimestre courant
    
    Bulletin bulletin; //Bulletin courant
    BulletinDAO bulletindao;
    ArrayList<Bulletin>allReports=new ArrayList<>(); //Tous les bulletins de la table
    
    

    /**
     * Creates new form Bulletin
     */
    public SchoolReport() {
        initComponents();
        
        fillQuarters();
        jLabel1.setText(inscription.getPersonne().getNom()+" "+inscription.getPersonne().getPrenom()+" "+inscription.getClasse().getNom());
        
        
    }
    
    //On récupère les 3 trimestres de l'année, s'il en manque les créer...
    public void fillQuarters(){
        
        try {
            quarterdao=new TrimestreDAO();
            allQuarters=quarterdao.all();
            
            quarters.addItem("None");
            
            //Remplir les choix de trimestre de l'année correspondante
            for(int i=0;i<allQuarters.size();i++){
                if(allQuarters.get(i).getAnnee().equals(classe.getAnnee())){
                    allQuarters.get(i).afficher(); //Un trimestre de l'année
                    int numero= allQuarters.get(i).getNumero();
                    quarters.addItem(""+numero);
                }
                
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SchoolReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quarters = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel2.setText("Trimestre:");

        quarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartersActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Moyenne min.", "Moyenne de l'élève", "Moyenne max.", "Appréciation"
            }
        ));
        jTable2.setRowHeight(40);
        jScrollPane1.setViewportView(jTable2);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setText("Appréciation générale:");

        jButton1.setText("Sauvegarder les modifications");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)))
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(293, 293, 293))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Retourne un trimestre de l'arraylist des trimestres en fonction de son numéro de trimestre (1,2 ou 3)
     * @return
     */
    public Trimestre findQuarter(int numero){
        Trimestre trimestre=null;
        
        for(int i=0;i<allQuarters.size();i++){
            if(allQuarters.get(i).getAnnee().equals(classe.getAnnee())){
                if(allQuarters.get(i).getNumero()==numero){
                    trimestre=allQuarters.get(i);
                }
                
            }
        }
        
        return trimestre;
        
    }
    
    
    //Choisir le trimestre correspondant à l'inscription (classe & etudiant) et afficher le bulletin
    //Si il n'existe pas, le créer.
    private void quartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartersActionPerformed
          
        if(quarters.getSelectedItem().equals("None")){
            
        }
        else{
        
                try {
                // TODO add your handling code here:
                
                bulletindao=new BulletinDAO();
                allReports=bulletindao.all();

                //Récuperer le trimestre sélectionné dans l'arraylist de trimestre,
                int numero=Integer.parseInt((String) quarters.getSelectedItem());           
                if(findQuarter(numero)!=null){
                    trimestre=findQuarter(numero);
                }
                else{
                    
                    throw new SQLException();
                }
                
                boolean reportfound=false;

                //Trouver le bulletin correspondant à l'inscription et le trimestre courant, se le bulletin n'existe pas, le créer
                for(int i=0;i<allReports.size();i++){
                    if(allReports.get(i).getInscription().equals(inscription)){
                        if(allReports.get(i).getTrimestre().equals(trimestre)){
                            bulletin=allReports.get(i);
                            reportfound=true;
                        }
                    }            
                }
                
                //Si bulletin non trouvé dans l'arraylist, le créer
                if(reportfound==false){
                    
                    int id_bulletin=0;
                    String appreciation="";                           
                    bulletin=new Bulletin(id_bulletin,appreciation,trimestre,inscription);
                    bulletin=bulletindao.create(bulletin);                          
                    allReports=bulletindao.all();
                }
                
                bulletin.afficher();
                
                //Et remplir les appréciations dans le tetArea
                fillReport();

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Bulletin non trouvé");
            }
        }
        

    }//GEN-LAST:event_quartersActionPerformed

    
    //Update un bulletin
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String appreciation=jTextArea1.getText();
        
        //Modifier une appréciation
        bulletin.setAppreciation(appreciation);
        bulletin.afficher();
        
        if(bulletin.equals(bulletindao.update(bulletin))){
            JOptionPane.showMessageDialog(rootPane, "Bulletin sauvegardé.");
            allReports=bulletindao.all();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     *Remplir le tableau de bulletin
     */
    public void fillReport(){
        jTextArea1.setText(bulletin.getAppreciation());
    }
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> quarters;
    // End of variables declaration//GEN-END:variables
}
